### ISSUE TITLE
cloud.ipynb でカーネルが変わらない

### ISSUE THREAD

**Issue by chuki** [seosoft/PyTorch-Intro-JP#1]
Microsoft Azure Notebook の"Kernel" → "Change kernel"からでないとカーネルが変えられなかった

**Comment by seosoft** [comment]
もしかして、変えられないというのはここのことですか？フォントサイズにもよるかもしれないけど、私のPCでも切れていて "3.6"とは表示されません。
が、ブルダウンを開くと、3 と 3.6 とが並んでます。

![notebooks_env_settings](https://user-images.githubusercontent.com/6135327/55274214-5e20b380-5319-11e9-90d1-31aa722ca3c5.jpg)

**Comment by chuki** [comment]
いえ、よくよく考えると、私がプルリク上げた個所でした。
Select Kernel　とか、そういうコマンドがあるのかと＾＾；
